### ISSUE TITLE
More specific infinite loader traversal insta, twitter, et. al.

### ISSUE THREAD

**Issue by N0taN3rd** [webrecorder/behaviors#29]
Is there more specific indicators that we are actually done loading all posts/tweets?

**Comment by N0taN3rd** [comment]
Twitter is more difficult than most best effort is knowing how many tweets a timeline has and tracking how many viewed

**Comment by ikreymer** [comment]
I guess it would be if there's some way to determine if at end of timeline, maybe there isn't anything that it sets in the dom that'd be apparent?

**Comment by ikreymer** [comment]
There's the 'Back to top' card that i think gets added, not sure if always or not.

**Comment by N0taN3rd** [comment]
The last time I checked Twitter adds the fail, done, loading markup to the dom at render time and makes them visible when appropriate. 

The counting approach seems simplest + maybe a visibility check.
