### ISSUE TITLE
Tweak instagram matching regex

### ISSUE THREAD

**Issue by N0taN3rd** [webrecorder/behaviors#31]
fails to work if query string present (https://www.instagram.com/eyebeamnyc/?hl=en)

currently matches on non-profile e.g. /account

**Comment by ikreymer** [comment]
Also should match home page, eg. instagram.com, if same behavior can be applied there (hopefully it can!)

**Comment by N0taN3rd** [comment]
your own feed behaves a tad bit more different than another users timeline.
it appears a new behavior will have to be created.
